#ifndef TREE_SITTER_COMMENT_TOKENS_H
#define TREE_SITTER_COMMENT_TOKENS_H

enum TokenType {
  T_TAGNAME,
  T_TAGTEXT,
  T_CODE_BLOCK_START,
  T_CODE_BLOCK_END,
  T_INVALID_TOKEN,
};

#endif /* ifndef TREE_SITTER_COMMENT_TOKENS_H */
