name: CI

on:
  push:
    branches:
      - main
      - zed
  pull_request:
    branches:
      - main
      - zed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          test-rust: true
          test-node: false
          test-python: true
          test-go: false
          test-swift: false
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          test-rust: true
          test-node: false
          test-python: true
          test-go: false
          test-swift: false
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          test-rust: true
          test-node: false
          test-python: true
          test-go: false
          test-swift: false
